### ISSUE TITLE
Provide the ability to document samples with translations

### ISSUE THREAD

**Issue by baywet** [DSB/oTranCe#33]
Hi,
As a translator I would like to be able to have access to samples for requested translations so I can understand the text needing translation better and provide a better translation.

As a developer I would like to be able to provide samples for certain translations so my translators have a better understanding of what needs to be translated.

This would be particularly useful when it comes to translate strings like 
'%1$s' decreased by %2$s and disappeared in %3$s compared to %4$s.

**Comment by DSB** [comment]
The connector is the solution for this case.
