### ISSUE TITLE
Provide the ability to add screenshots with translations

### ISSUE THREAD

**Issue by baywet** [DSB/oTranCe#34]
Hi,
As a translator I would like to be able to see a screenshot of the application with the translation so I can have a better understanding of what is to be translated.
As a developer I want to provide screenshots of the application with translations so translators have a better understanding of what has to be translated.

**Comment by DSB** [comment]
Meanwhile the connector is described in the oTranCe wiki: https://mysqldumper.jira.com/wiki/display/OTC/Connect+your+application+with+oTranCe
