### ISSUE TITLE
Translation review by the community

### ISSUE THREAD

**Issue by baywet** [DSB/oTranCe#36]
As a user of the translated application (or member of the community) I would like to be able to vote for the quality of a translation and propose an alternative translation but not edit the actual translation. Then the program manager or translation reviewer for this language could challenge translators based on that.

This would allow scenarios like quality testing of the translations by beta testers and feedback providing

**Comment by DSB** [comment]
There are other solutions out there that offer such features. oTranCe doesn't try to catch all such cases but wants to stay simple and fast in the workflow.
