### ISSUE TITLE
File Templates - JSON Export, last comma

### ISSUE THREAD

**Issue by roest01** [DSB/oTranCe#52]
Hello,

We have a file template providing a JSON as a result with all the key value pairs.
But, because we need valid JSON from oTransCe, we need to clean up the last comma from the export result.

A current export looking like this:

``` json
{
"header.menu.home": "Home",
"header.menu.logout": "Logout",
}
```

As you see we got a , behind the last entry which makes the JSON invalid.
Our template looks like this:
![otransce_filetemplates](https://cloud.githubusercontent.com/assets/2870718/16950921/de3bdc02-4dc2-11e6-85cd-5b035d1cbd3b.png)

**i have different solution ideas but wanna ask you guys if you see a best practice which allow me to return my solution as PR**
## Solutions
1. put a dummy entry in the footer without the ending , (more a workarount)
2. put a dummy entry in the header and prepend the comma (like 1. but another style)
3. add a field "last line" which can be configurable within the template and get used for the last key value pair only (maybe to exaggerated?)
4. _any ideas of you?_

Thanks Tobias

**Comment by DSB** [comment]
Sorry for my late response. Currently  I'd go with 1 to get valid files with no effort.
In the long run the export should be based on specialised exporters like it is done with the importers. Then one could add format specific things to it. I have no plans to implement soemthing like that but as always I'm open for pull requests. ;)

**Comment by roest01** [comment]
thank you, for the moment we keep using 1 ;)
