### ISSUE TITLE
usage of smallint in keys table

### ISSUE THREAD

**Issue by roest01** [DSB/oTranCe#56]
As user we run into a problem having more than **65535** translations in our database.
The consequence was simple, the oTransCe saves no more translation.

Because we're in 2017 in my opinion there is no reason to use _smallint_ anymore.

Therefore i suggest to replace every occurrence of _smallint_ with int.
I will create a pull request for that bug, we already fixed the problem in our installation.

**Comment by DSB** [comment]
I totally agree with you and look forward to your pr.
Thanks for participating in this project.

**Comment by roest01** [comment]
#57
