### ISSUE TITLE
feature request : enable to have 2 project

### ISSUE THREAD

**Issue by delcroip** [DSB/oTranCe#60]
hi ,
 
I tried to install two Otrance on a single server but once one otrance is launched I can't access to the other one ( display first otrance).

Can you develop a way to have two projects in a single instance.? 

br

**Comment by DSB** [comment]
Hi,

I don't understand the issue. You can create two sub domains which forward into each otrance installation. Make sure to configure 2 different databases or use different prefixes inside one database.
